server:
  host: 0.0.0.0
  port: 5000
center:
  url: http://127.0.0.1:8080
  agent_id: agent-001
  pull_interval: 60
snmp:
  community: Mrtg.Dikong
ssh:
  username: root
  password: abcd#123456
logs:
  level: warning